### ISSUE TITLE
Error trying to run

### ISSUE THREAD

**Issue by Magu99** [wookayin/gpustat#110]
Didn't work, running debug got this message:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gpustat/__main__.py", line 19, in print_gpustat
    gpu_stats = GPUStatCollection.new_query()
  File "/usr/lib/python3/dist-packages/gpustat/core.py", line 281, in new_query
    N.nvmlInit()
  File "/usr/lib/python3/dist-packages/pynvml.py", line 615, in nvmlInit
    _nvmlCheckReturn(ret)
  File "/usr/lib/python3/dist-packages/pynvml.py", line 310, in _nvmlCheckReturn
    raise NVMLError(ret)
**pynvml.NVMLError_DriverNotLoaded: Driver Not Loaded**

Don't know if

**Comment by XuehaiPan** [comment]
@Magu99 If you are using Linux, this is caused by the driver module is not loaded by the Linux kernel.

It may be caused by upgrading your kernel without rebuilding your NVIDIA driver module. Usually, it may arise when you install the driver using the `.run` file then upgrade your Linux kernel.

**Comment by wookayin** [comment]
As @XuehaiPan suggested, please reinstall the nvidia-driver and make sure `nvidia-smi` works.

To see whether nvidia driver has been loaded on your kernel:
```
lsmod | grep nvidia
```
