### ISSUE TITLE
WINDOWS: querying a psutil process can fail with psutil.AccessDenied

### ISSUE THREAD

**Issue by mattip** [wookayin/gpustat#121]
gpustat is used in [ray's dashboard](https://docs.ray.io/en/latest/ray-core/ray-dashboard.html) to gather GPU info. When running `python -m gpustat --debug` I am seeing an exception when querying the username of a process (in this case it is a windows service called [dwm.exe](https://www.howtogeek.com/howto/windows-vista/what-is-dwmexe-and-why-is-it-running/) running windows display compositing service):
```
>python -m gpustat --debug
Error on querying NVIDIA devices. Use --debug flag for details
Traceback (most recent call last):
  File "d:\miniconda\envs\ray_test\lib\site-packages\psutil\_pswindows.py", line 688, in wrapper
    return fun(self, *args, **kwargs)
  File "d:\miniconda\envs\ray_test\lib\site-packages\psutil\_pswindows.py", line 934, in username
    domain, user = cext.proc_username(self.pid)
PermissionError: [WinError 5] Access is denied: '(originated from OpenProcess)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\pypy_stuff\gpustat\gpustat\cli.py", line 20, in print_gpustat
    gpu_stats = GPUStatCollection.new_query(debug=debug)
  File "d:\pypy_stuff\gpustat\gpustat\core.py", line 536, in new_query
    gpu_info = get_gpu_info(handle)
  File "d:\pypy_stuff\gpustat\gpustat\core.py", line 485, in get_gpu_info
    process = get_process_info(nv_process)
  File "d:\pypy_stuff\gpustat\gpustat\core.py", line 382, in get_process_info
    process['username'] = ps_process.username()
  File "d:\miniconda\envs\ray_test\lib\site-packages\psutil\__init__.py", line 709, in username
    return self._proc.username()
  File "d:\miniconda\envs\ray_test\lib\site-packages\psutil\_pswindows.py", line 690, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.AccessDenied: (pid=1720)
```

Would a solution be to add another exception stanza to the ones already wrapping [the `get_process_info()` call](https://github.com/wookayin/gpustat/blob/847f87e531432b603c805f2289621e73881f653d/gpustat/core.py#L485) to catch the exception?

**Comment by wookayin** [comment]
Thanks for the suggestion. This is definitely a corner case that happens in Windows. Let me try fixing this soon.

**Comment by mattip** [comment]
I can confirm that this fixes the issue, `python -m gpustat --debug` no longer crashes

**Comment by mattip** [comment]
On the one hand I am the only responder to this issue: the OP has not responded since opening it, so I am inclined to close it. On the other, there is a known failure with gpustat on windows when using nvidia drivers for system processes. While the issue was fixed, gpustat has not made an official release in over a year. Maybe we should vendor the HEAD of gpustat into the dashboard agent code?
