### ISSUE TITLE
gpustat --debug: pynvml.NVMLError_LibraryNotFound: NVML Shared Library Not Found

### ISSUE THREAD

**Issue by Jasha10** [wookayin/gpustat#134]
I'm having a similar issue to #35.
Here is my system info:
os: Ubuntu 20.04
```text
$ gpustat --version
gpustat 1.0.0
```
```text
$ gpustat --debug
Error on querying NVIDIA devices. Use --debug flag for details
Traceback (most recent call last):
  File "/home/rig1/.local/pipx/venvs/gpustat/lib/python3.10/site-packages/pynvml.py", line 1478, in _LoadNvmlLibrary
    nvmlLib = CDLL("libnvidia-ml.so.1")
  File "/home/linuxbrew/.linuxbrew/opt/python@3.10/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libnvidia-ml.so.1: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rig1/.local/pipx/venvs/gpustat/lib/python3.10/site-packages/gpustat/cli.py", line 18, in print_gpustat
    gpu_stats = GPUStatCollection.new_query(debug=debug)
  File "/home/rig1/.local/pipx/venvs/gpustat/lib/python3.10/site-packages/gpustat/core.py", line 370, in new_query
    N.nvmlInit()
  File "/home/rig1/.local/pipx/venvs/gpustat/lib/python3.10/site-packages/pynvml.py", line 1450, in nvmlInit
    nvmlInitWithFlags(0)
  File "/home/rig1/.local/pipx/venvs/gpustat/lib/python3.10/site-packages/pynvml.py", line 1433, in nvmlInitWithFlags
    _LoadNvmlLibrary()
  File "/home/rig1/.local/pipx/venvs/gpustat/lib/python3.10/site-packages/pynvml.py", line 1480, in _LoadNvmlLibrary
    _nvmlCheckReturn(NVML_ERROR_LIBRARY_NOT_FOUND)
  File "/home/rig1/.local/pipx/venvs/gpustat/lib/python3.10/site-packages/pynvml.py", line 765, in _nvmlCheckReturn
    raise NVMLError(ret)
pynvml.NVMLError_LibraryNotFound: NVML Shared Library Not Found
```
```text
$ nvidia-smi
Mon Sep 26 17:22:56 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.65.01    Driver Version: 515.65.01    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:01:00.0  On |                  N/A |
|  0%   54C    P5    46W / 420W |   1145MiB / 24576MiB |     31%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  On   | 00000000:41:00.0 Off |                  N/A |
|  0%   35C    P8    31W / 420W |     10MiB / 24576MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1895      G   /usr/lib/xorg/Xorg                187MiB |
|    0   N/A  N/A      2674      G   /usr/lib/xorg/Xorg                529MiB |
|    0   N/A  N/A      2816      G   /usr/bin/gnome-shell               87MiB |
|    0   N/A  N/A      3185      G   ...AAAAAAAAA= --shared-files       52MiB |
|    0   N/A  N/A     20577      G   /usr/lib/firefox/firefox          140MiB |
|    1   N/A  N/A      1895      G   /usr/lib/xorg/Xorg                  4MiB |
|    1   N/A  N/A      2674      G   /usr/lib/xorg/Xorg                  4MiB |
+-----------------------------------------------------------------------------+
```

**Comment by wookayin** [comment]
Can you show the output of `ldconfig -p | grep libnvidia-ml`? It should print something if nvidia driver is properly installed:

```
$ ldconfig -p | grep libnvidia-ml
	libnvidia-ml.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1
	libnvidia-ml.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-ml.so
```

How did you installed nvidia drivers?

**Comment by wookayin** [comment]
I'm going to close this issue due to inactivity, assuming the nvidia driver or nvidia-smi installation was not appropriate.

**Comment by Jasha10** [comment]
Sorry I missed your previous message.
> Can you show the output of `ldconfig -p | grep libnvidia-ml`?

I'm getting no output:
```text
$ ldconfig -p | grep libnvidia-ml
$
```

**Comment by Jasha10** [comment]
> assuming the nvidia driver or nvidia-smi installation was not appropriate

What's strange is that the GPUs seem to be working fine and the `nvidia-smi` is working too.

**Comment by wookayin** [comment]
> I'm getting no output:

This is why it's not working. But what's strange is that all the dynamics libraries from `ldconfig -p` are from linuxbrew. Perhaps linuxbrew is overriding LD_LIBRARY_PATH completely. You can check out `/etc/ld.so.conf` and `/etc/ld.so.conf.d/*`; one of the conf files will contain path to SYSTEM libraries (e.g. `/lib/x86_64-linux-gnu` in Ubuntu systems).

What is the path of `nvidia-smi`? (`which -a nvidia-smi`) How did you install the drivers?

**Comment by Jasha10** [comment]
> It might well be that `ldconfig` itself is coming from homebrew?

Yes, it seems `ldconfig` was provided by linuxbrew's glibc formula.
```text
$ which -a ldconfig
/home/linuxbrew/.linuxbrew/sbin/ldconfig
/usr/sbin/ldconfig
/sbin/ldconfig
```
After commenting out my `~/.bashrc` file so that linuxbrew is no longer active, I'm getting the following from ldconfig:
```text
$ ldconfig -p | grep libnvidia-ml
	libnvidia-ml.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libnvidia-ml.so.1
	libnvidia-ml.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libnvidia-ml.so
```
After commenting out `.bashrc`, I'm now getting different output from `gpustat`:
```text
$ python3 -m venv tmp_venv
$ source tmp_venv/bin/activate
$ pip install gpustat
$ gpustat --debug
Error on querying NVIDIA devices. Use --debug flag for details
Traceback (most recent call last):
  File "/home/rig1/tmp_venv/lib/python3.10/site-packages/gpustat/cli.py", line 18, in print_gpustat
    gpu_stats = GPUStatCollection.new_query(debug=debug)
  File "/home/rig1/tmp_venv/lib/python3.10/site-packages/gpustat/core.py", line 370, in new_query
    N.nvmlInit()
  File "/home/rig1/tmp_venv/lib/python3.10/site-packages/pynvml.py", line 1450, in nvmlInit
    nvmlInitWithFlags(0)
  File "/home/rig1/tmp_venv/lib/python3.10/site-packages/pynvml.py", line 1440, in nvmlInitWithFlags
    _nvmlCheckReturn(ret)
  File "/home/rig1/tmp_venv/lib/python3.10/site-packages/pynvml.py", line 765, in _nvmlCheckReturn
    raise NVMLError(ret)
pynvml.NVMLError_LibRmVersionMismatch: RM has detected an NVML/RM version mismatch.
```

**Comment by Jasha10** [comment]
> What is the path of `nvidia-smi`? (`which -a nvidia-smi`)

Hmm, it seems `nvidia-smi` is no longer installed on my system. It *was* working last week when I opened this issue. The change between now and then is I upgraded from ubuntu 20.04 to 22.04.

> How did you install the drivers?

I believe I installed them from the nvidia.com downloads page.

**Comment by Jasha10** [comment]
Upon further investigation, I'd installed `gpustat` using `pipx`, and I'd installed `pipx` using linuxbrew.

The problem is solved by installing `gpustat` via a python version that is *not* provided by linuxbrew.
