### ISSUE TITLE
No process info, just "Not Supported"

### ISSUE THREAD

**Issue by sandove** [wookayin/gpustat#138]
This tool is really useful, but I encounted a problem.

**What I tried**
➜ gpustat
```
seccontent-kg-application011164206223.et135  Thu Oct 13 14:42:31 2022  450.36.06
[0] Tesla V100-SXM2-32GB | 56°C, 100 % | 30022 / 32510 MB | (Not Supported)
[1] Tesla V100-SXM2-32GB | 50°C,  89 % | 32374 / 32510 MB | (Not Supported)
[2] Tesla V100-SXM2-32GB | 46°C,  91 % | 15660 / 32510 MB | (Not Supported)
[3] Tesla V100-SXM2-32GB | 45°C,  42 % |  8416 / 32510 MB | (Not Supported)
```

➜ gpustat --debug
```
> An error while retrieving `fan_speed`: Not Supported
Traceback (most recent call last):
  File "/test/myname/miniconda3/envs/torch1.8/lib/python3.8/site-packages/gpustat/core.py", line 452, in get_gpu_info
    fan_speed = N.nvmlDeviceGetFanSpeed(handle)
  File "/test/myname/miniconda3/envs/torch1.8/lib/python3.8/site-packages/pynvml.py", line 1942, in nvmlDeviceGetFanSpeed
    _nvmlCheckReturn(ret)
  File "/test/myname/miniconda3/envs/torch1.8/lib/python3.8/site-packages/pynvml.py", line 765, in _nvmlCheckReturn
    raise NVMLError(ret)
pynvml.NVMLError_NotSupported: Not Supported

> An error while retrieving `compute_processes`: Function Not Found
Traceback (most recent call last):
  File "/test/myname/miniconda3/envs/torch1.8/lib/python3.8/site-packages/pynvml.py", line 782, in _nvmlGetFunctionPointer
    _nvmlGetFunctionPointer_cache[name] = getattr(nvmlLib, name)
  File "/test/myname/miniconda3/envs/torch1.8/lib/python3.8/ctypes/__init__.py", line 386, in __getattr__
    func = self.__getitem__(name)
  File "/test/myname/miniconda3/envs/torch1.8/lib/python3.8/ctypes/__init__.py", line 391, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/nvidia-450/libnvidia-ml.so.1: undefined symbol: nvmlDeviceGetComputeRunningProcesses_v2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/test/myname/miniconda3/envs/torch1.8/lib/python3.8/site-packages/gpustat/core.py", line 495, in get_gpu_info
    N.nvmlDeviceGetComputeRunningProcesses(handle)
  File "/test/myname/miniconda3/envs/torch1.8/lib/python3.8/site-packages/pynvml.py", line 2223, in nvmlDeviceGetComputeRunningProcesses
    return nvmlDeviceGetComputeRunningProcesses_v2(handle);
  File "/test/myname/miniconda3/envs/torch1.8/lib/python3.8/site-packages/pynvml.py", line 2191, in nvmlDeviceGetComputeRunningProcesses_v2
    fn = _nvmlGetFunctionPointer("nvmlDeviceGetComputeRunningProcesses_v2")
  File "/test/myname/miniconda3/envs/torch1.8/lib/python3.8/site-packages/pynvml.py", line 785, in _nvmlGetFunctionPointer
    raise NVMLError(NVML_ERROR_FUNCTION_NOT_FOUND)
pynvml.NVMLError_FunctionNotFound: Function Not Found

> An error while retrieving `graphics_processes`: Function Not Found
Traceback (most recent call last):
  File "/test/myname/miniconda3/envs/torch1.8/lib/python3.8/site-packages/pynvml.py", line 782, in _nvmlGetFunctionPointer
    _nvmlGetFunctionPointer_cache[name] = getattr(nvmlLib, name)
  File "/test/myname/miniconda3/envs/torch1.8/lib/python3.8/ctypes/__init__.py", line 386, in __getattr__
    func = self.__getitem__(name)
  File "/test/myname/miniconda3/envs/torch1.8/lib/python3.8/ctypes/__init__.py", line 391, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/nvidia-450/libnvidia-ml.so.1: undefined symbol: nvmlDeviceGetGraphicsRunningProcesses_v2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/test/myname/miniconda3/envs/torch1.8/lib/python3.8/site-packages/gpustat/core.py", line 501, in get_gpu_info
    N.nvmlDeviceGetGraphicsRunningProcesses(handle)
  File "/test/myname/miniconda3/envs/torch1.8/lib/python3.8/site-packages/pynvml.py", line 2260, in nvmlDeviceGetGraphicsRunningProcesses
    return nvmlDeviceGetGraphicsRunningProcesses_v2(handle)
  File "/test/myname/miniconda3/envs/torch1.8/lib/python3.8/site-packages/pynvml.py", line 2228, in nvmlDeviceGetGraphicsRunningProcesses_v2
    fn = _nvmlGetFunctionPointer("nvmlDeviceGetGraphicsRunningProcesses_v2")
  File "/test/myname/miniconda3/envs/torch1.8/lib/python3.8/site-packages/pynvml.py", line 785, in _nvmlGetFunctionPointer
    raise NVMLError(NVML_ERROR_FUNCTION_NOT_FOUND)
pynvml.NVMLError_FunctionNotFound: Function Not Found

> An error while retrieving `fan_speed`: Not Supported -> Total 4 occurrences.
> An error while retrieving `compute_processes`: Function Not Found -> Total 4 occurrences.
> An error while retrieving `graphics_processes`: Function Not Found -> Total 4 occurrences.
```

However, "nvidia-smi" works well:
➜ nvidia-smi
![image](https://user-images.githubusercontent.com/20484005/195522557-d0f91b34-7597-4cd4-b004-7b98e8e76fcc.png)

I tried re-install "nvidia-ml-py3" 11.495.46, still not works.
More information:
![image](https://user-images.githubusercontent.com/20484005/195524800-dd7477d2-8af6-4885-b0a4-f7651cbcabce.png)

"ldconfig -p | grep nvidia-ml " result:
![image](https://user-images.githubusercontent.com/20484005/195524189-2d47de67-22ef-4a8a-98c1-b23ee83c7a3e.png)

**Problem**
No process information.

**Details**
OS Ubuntu 16.04.7 LTS
GPU Tesla V100-SXM2-32GB

Could any one help? 
Thanks.

**Comment by wookayin** [comment]
Your nvidia driver version is 450.36. Since gpustat 1.0, you'll need to install driver version R450.66 or higher. See #107 for why.

**Comment by sandove** [comment]
> 

Yes, I switch to gpustat 0.6.0 and it works fine. Thank you!
