### ISSUE TITLE
Installation instruction for RockyLinux 8 (EL8)

### ISSUE THREAD

**Issue by OleHolmNielsen** [wookayin/gpustat#174]
Thanks a lot for the great gpustat tool!  I'm trying to integrate this into my Slurm cluster monitoring tools.

Could you kindly add instructions for RockyLinux 8.10 (and other RHEL 8 clones)? On our systems working installation instructions seem to be:
```
# dnf install gcc python3-devel
# pip3 install setuptools-scm
# pip3 install gpustat 
```
Here is what happens with the current installation instructions:
```
# pip install gpustat
-bash: pip: command not found
```
On EL8 one must use pip3 in stead:
```
# pip3 install gpustat
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Collecting gpustat
  Downloading https://files.pythonhosted.org/packages/79/c4/46d005aec3bf911cb030467d91e062a5386ff4a03e51874424cacc0f60c1/gpustat-1.1.1.tar.gz (98kB)
    100% |████████████████████████████████| 102kB 1.5MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/tmp/pip-build-bbxdr8yp/gpustat/setup.py", line 18, in read_version
        import setuptools_scm
    ModuleNotFoundError: No module named 'setuptools_scm'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-bbxdr8yp/gpustat/setup.py", line 37, in <module>
        __version__ = read_version()
      File "/tmp/pip-build-bbxdr8yp/gpustat/setup.py", line 21, in read_version
        "setuptools_scm not found. When running setup.py directly, "
    ImportError: setuptools_scm not found. When running setup.py directly, setuptools_scm needs to be installed manually. Or consider running `pip install -e .` instead.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-bbxdr8yp/gpustat/
```
Installing the setuptools-scm module seems to fix this issue.

**Environment information:**

 - OS:
NAME="Rocky Linux"
VERSION="8.10 (Green Obsidian)"

**Comment by wookayin** [comment]
You may want to install `python3-pip` instead. `python3 -m pip` in place of `pip` would work.

**Comment by OleHolmNielsen** [comment]
Thanks for recommending ```python3 -m pip``` in stead of ```pip3```.
I have now reinstalled a node with a minimal RockyLinux 8.10 system as a test, and the simple "pip install" also fails as before:
```
$ python3 -m pip install gpustat
WARNING: Running pip install with root privileges is generally not a good idea. Try `__main__.py install --user` instead.
Collecting gpustat
  Downloading https://files.pythonhosted.org/packages/79/c4/46d005aec3bf911cb030467d91e062a5386ff4a03e51874424cacc0f60c1/gpustat-1.1.1.tar.gz (98kB)
    100% |████████████████████████████████| 102kB 1.6MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/tmp/pip-build-dsrjtxz8/gpustat/setup.py", line 18, in read_version
        import setuptools_scm
    ModuleNotFoundError: No module named 'setuptools_scm'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-dsrjtxz8/gpustat/setup.py", line 37, in <module>
        __version__ = read_version()
      File "/tmp/pip-build-dsrjtxz8/gpustat/setup.py", line 21, in read_version
        "setuptools_scm not found. When running setup.py directly, "
    ImportError: setuptools_scm not found. When running setup.py directly, setuptools_scm needs to be installed manually. Or consider running `pip install -e .` instead.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-dsrjtxz8/gpustat/
```

Could you please add to your README.md instructions that will work on EL8 Linux systems?  The commands including mandatory prerequisites are:
```clush -bg camd
$ dnf install gcc python3-devel
$ python3 -m pip install setuptools-scm
$ python3 -m pip install gpustat 
```
On a RockyLinux 9.5 system, however, I can confirm that the normal command ```pip install gpustat``` works as expected.
Since a lot of Linux clusters are running RockyLinux 8 (or other EL8 versions) at this time, it would be great if you could add installation instructions that work on EL8.

Thanks a lot,
Ole

**Comment by wookayin** [comment]
Thanks for providing additional information. So `setuptools-scm` needs to be installed on the "system" python. However, I'd like to close this issue, since I believe this is more related to (possibly broken) python environment in Rocky Linux systems.
