### ISSUE TITLE
rxvt-unicode support

### ISSUE THREAD

**Issue by Rizhiy** [wookayin/gpustat#34]
I have a very strange situation, I currently use `urxvt` as a terminal and gpustat does not start from bare terminal raising:
```
Traceback (most recent call last):
  File "/home/rizhiy/anaconda3/bin/gpustat", line 7, in <module>
    from gpustat import main
  File "/home/rizhiy/anaconda3/lib/python3.6/site-packages/gpustat.py", line 32, in <module>
    class GPUStat(object):
  File "/home/rizhiy/anaconda3/lib/python3.6/site-packages/gpustat.py", line 156, in GPUStat
    term=Terminal(),
  File "/home/rizhiy/anaconda3/lib/python3.6/site-packages/blessings/__init__.py", line 105, in __init__
    self._init_descriptor)
_curses.error: setupterm: could not find terminal
```
So looks like `blessings` does not recognise `urxvt` properly.

But when I start gputstat from within the `tmux` it starts ok, but doesn't use correct colors (e.g. uses standard black instead of bold_black).

What version of `blessings` are you using? Does this problem exist in the current version?

**Comment by wookayin** [comment]
I am using blessings==1.6. However, the specification of term codes are defined in system libraries (ncurses or terminfo, see [this comment](https://github.com/wookayin/gpustat/issues/32#issuecomment-346894894)), not on the blessing package. Maybe we need to work around in that case, but I do not currently have `urxvt`.

**Comment by wookayin** [comment]
Maybe we should force the `Terminal` instance to not look up for `urxvt`. Do you have any idea?

**Comment by slavaGanzin** [comment]
It works in `rxvt-unicode (urxvt) v9.22 - released: 2016-01-23`

**Comment by wangg12** [comment]
I also encountered this issue on Ubuntu 16.04, @wookayin do you know how to solve it?
```
Traceback (most recent call last):
  File "anaconda3/envs/py36/bin/gpustat", line 6, in <module>
    from gpustat import main
  File "anaconda3/envs/py36/lib/python3.6/site-packages/gpustat/__init__.py", line 7, in <module>
    from .core import GPUStat, GPUStatCollection
  File "anaconda3/envs/py36/lib/python3.6/site-packages/gpustat/core.py", line 31, in <module>
    class GPUStat(object):
  File "anaconda3/envs/py36/lib/python3.6/site-packages/gpustat/core.py", line 161, in GPUStat
    term=Terminal(),
  File "anaconda3/envs/py36/lib/python3.6/site-packages/blessings/__init__.py", line 98, in __init__
    self._init_descriptor)
_curses.error: setupterm: could not find terminfo database
```

**Comment by wookayin** [comment]
what do your $TERM and $TERMINFO variable read?

**Comment by wangg12** [comment]
`$TERM` is `xterm` and  `$TERMINFO` is empty.

**Comment by wookayin** [comment]
Check the following directories: `~/.terminfo`, `/etc/terminfo`, `/lib/terminfo`, `/usr/share/terminfo`. Your terminfo seems to be broken.

**Comment by wangg12** [comment]
I figured out the problem. I copied my anaconda from another machine and the path does not match the original path. I solved it by using symlink.

**Comment by DarthThomas** [comment]
> I figured out the problem. I copied my anaconda from another machine and the path does not match the original path. I solved it by using symlink.

Hi! I got the same problem, I changed some shebang and modified .bashrc to make conda work. But _curses.error: setupterm: could not find terminfo database is still here. Would you share how did you symlink(which file) and solved the problem?

**Comment by ck853178967** [comment]
My command for reference
`ln -s ~/anaconda3/lib/terminfo ~/.terminfo`
